name: CI

on:
  push:
    branches:
    - master
  pull_request:
    - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: xcodebuild build
